export const SEASONS = [
  "英雄联盟传奇 (S16)",
  "瑞兽闹新春 (S4.5)"
];

export interface Hero {
  name: string;
  season: string;
  cost: number;
  origin: string[];
  job: string[];
  avatar: string;
}

export const HERO_DATA: Hero[] = [
  // 英雄联盟传奇 (S16)
  { name: "露露", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["约德尔人"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-lulu/100/100" },
  { name: "兰博", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["约德尔人"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-rumble/100/100" },
  { name: "俄洛伊", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["比尔吉沃特"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-illaoi/100/100" },
  { name: "贝蕾亚", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["诺克萨斯"], job: ["裁决战士", "主宰"], avatar: "https://picsum.photos/seed/tft-belveth/100/100" },
  { name: "嘉文四世", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["德玛西亚"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-jarvaniv/100/100" },
  { name: "娑娜", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["德玛西亚"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-sona/100/100" },
  { name: "艾尼维亚", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["弗雷尔卓德"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-anivia/100/100" },
  { name: "凯特琳", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["皮尔特沃夫"], job: ["狙神"], avatar: "https://picsum.photos/seed/tft-caitlyn/100/100" },
  { name: "慎", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["艾欧尼亚"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-shen/100/100" },
  { name: "科格莫", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["虚空"], job: ["法师", "狙神"], avatar: "https://picsum.photos/seed/tft-kogmaw/100/100" },
  { name: "烬", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["艾欧尼亚"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-jhin/100/100" },
  { name: "佛耶戈", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["暗影岛"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-viego/100/100" },
  { name: "奇亚娜", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["以绪塔尔"], job: ["裁决战士"], avatar: "https://picsum.photos/seed/tft-qiyana/100/100" },
  { name: "布里茨", season: "英雄联盟传奇 (S16)", cost: 1, origin: ["祖安"], job: ["主宰"], avatar: "https://picsum.photos/seed/tft-blitzcrank/100/100" },
  { name: "崔丝塔娜", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["约德尔人"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-tristana/100/100" },
  { name: "提莫", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["约德尔人"], job: ["狙神"], avatar: "https://picsum.photos/seed/tft-teemo/100/100" },
  { name: "崔斯特", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["比尔吉沃特"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-twistedfate/100/100" },
  { name: "赛恩", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["诺克萨斯"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-sion/100/100" },
  { name: "厄斐琉斯", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["巨神峰"], job: [], avatar: "https://picsum.photos/seed/tft-aphelios/100/100" },
  { name: "艾希", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["弗雷尔卓德"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-ashe/100/100" },
  { name: "妮蔻", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["以绪塔尔"], job: ["法师", "护卫"], avatar: "https://picsum.photos/seed/tft-neeko/100/100" },
  { name: "蔚", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["皮尔特沃夫", "祖安"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-vi/100/100" },
  { name: "亚索", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["艾欧尼亚"], job: ["裁决战士"], avatar: "https://picsum.photos/seed/tft-yasuo/100/100" },
  { name: "雷克塞", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["虚空"], job: ["征服者"], avatar: "https://picsum.photos/seed/tft-reksai/100/100" },
  { name: "科加斯", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["虚空"], job: ["主宰"], avatar: "https://picsum.photos/seed/tft-chogath/100/100" },
  { name: "波比", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["德玛西亚", "约德尔人"], job: ["主宰"], avatar: "https://picsum.photos/seed/tft-poppy/100/100" },
  { name: "泰达米尔", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["弗雷尔卓德"], job: ["裁决战士"], avatar: "https://picsum.photos/seed/tft-tryndamere/100/100" },
  { name: "格雷福斯", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["比尔吉沃特"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-graves/100/100" },
  { name: "艾克", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["祖安"], job: ["耀光使"], avatar: "https://picsum.photos/seed/tft-ekko/100/100" },
  { name: "巴德", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["星界游神"], job: [], avatar: "https://picsum.photos/seed/tft-bard/100/100" },
  { name: "赵信", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["德玛西亚", "艾欧尼亚"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-xinzhao/100/100" },
  { name: "约里克", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["暗影岛"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-yorick/100/100" },
  { name: "奥莉安娜", season: "英雄联盟传奇 (S16)", cost: 2, origin: ["皮尔特沃夫"], job: ["神谕者"], avatar: "https://picsum.photos/seed/tft-orianna/100/100" },
  { name: "诺提勒斯", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["比尔吉沃特"], job: ["主宰", "神盾使"], avatar: "https://picsum.photos/seed/tft-nautilus/100/100" },
  { name: "普朗克", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["比尔吉沃特"], job: ["裁决战士", "征服者"], avatar: "https://picsum.photos/seed/tft-gangplank/100/100" },
  { name: "德莱文", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["诺克萨斯"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-draven/100/100" },
  { name: "佐伊", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["巨神峰"], job: [], avatar: "https://picsum.photos/seed/tft-zoe/100/100" },
  { name: "蕾欧娜", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["巨神峰"], job: [], avatar: "https://picsum.photos/seed/tft-leona/100/100" },
  { name: "米利欧", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["以绪塔尔"], job: ["神谕者"], avatar: "https://picsum.photos/seed/tft-milio/100/100" },
  { name: "金克丝", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["祖安"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-jinx/100/100" },
  { name: "阿狸", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["艾欧尼亚"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-ahri/100/100" },
  { name: "玛尔扎哈", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["虚空"], job: ["耀光使"], avatar: "https://picsum.photos/seed/tft-malzahar/100/100" },
  { name: "瑟庄妮", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["弗雷尔卓德"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-sejuani/100/100" },
  { name: "德莱厄斯", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["诺克萨斯"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-darius/100/100" },
  { name: "凯南", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["艾欧尼亚", "约德尔人"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-kennen/100/100" },
  { name: "格温", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["暗影岛"], job: ["耀光使"], avatar: "https://picsum.photos/seed/tft-gwen/100/100" },
  { name: "乐芙兰", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["诺克萨斯"], job: ["神谕者"], avatar: "https://picsum.photos/seed/tft-leblanc/100/100" },
  { name: "薇恩", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["德玛西亚"], job: ["狙神"], avatar: "https://picsum.photos/seed/tft-vayne/100/100" },
  { name: "洛里斯", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["皮尔特沃夫"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-loris/100/100" },
  { name: "蒙多医生", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["祖安"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-drmundo/100/100" },
  { name: "可酷伯与悠米", season: "英雄联盟传奇 (S16)", cost: 3, origin: ["约德尔人"], job: ["斗士", "神谕者"], avatar: "https://picsum.photos/seed/tft-kobuko_and_yuumi/100/100" },
  { name: "厄运小姐", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["比尔吉沃特"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-missfortune/100/100" },
  { name: "安蓓萨", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["诺克萨斯"], job: ["征服者"], avatar: "https://picsum.photos/seed/tft-ambessa/100/100" },
  { name: "塔里克", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["巨神峰"], job: [], avatar: "https://picsum.photos/seed/tft-taric/100/100" },
  { name: "盖伦", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["德玛西亚"], job: ["护卫"], avatar: "https://picsum.photos/seed/tft-garen/100/100" },
  { name: "拉克丝", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["德玛西亚"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-lux/100/100" },
  { name: "布隆", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["弗雷尔卓德"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-braum/100/100" },
  { name: "丽桑卓", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["弗雷尔卓德"], job: ["神谕者"], avatar: "https://picsum.photos/seed/tft-lissandra/100/100" },
  { name: "萨勒芬妮", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["皮尔特沃夫"], job: ["耀光使"], avatar: "https://picsum.photos/seed/tft-seraphine/100/100" },
  { name: "孙悟空", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["艾欧尼亚"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-wukong/100/100" },
  { name: "卑尔维斯", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["虚空"], job: ["裁决战士"], avatar: "https://picsum.photos/seed/tft-belveth_4/100/100" },
  { name: "辛吉德", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["祖安"], job: ["主宰"], avatar: "https://picsum.photos/seed/tft-singed/100/100" },
  { name: "维迦", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["约德尔人"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-veigar/100/100" },
  { name: "永恩", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["艾欧尼亚"], job: ["裁决战士"], avatar: "https://picsum.photos/seed/tft-yone/100/100" },
  { name: "沃里克", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["祖安"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-warwick_4/100/100" },
  { name: "菲兹", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["比尔吉沃特", "约德尔人"], job: [], avatar: "https://picsum.photos/seed/tft-fizz/100/100" },
  { name: "奈德丽", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["以绪塔尔"], job: ["狂野女猎手"], avatar: "https://picsum.photos/seed/tft-nidalee/100/100" },
  { name: "峡谷先锋", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["虚空"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-riftherald/100/100" },
  { name: "斯卡纳", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["以绪塔尔"], job: [], avatar: "https://picsum.photos/seed/tft-skarner/100/100" },
  { name: "黛安娜", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["巨神峰"], job: [], avatar: "https://picsum.photos/seed/tft-diana/100/100" },
  { name: "卡莎", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["虚空之女", "虚空"], job: ["狙神"], avatar: "https://picsum.photos/seed/tft-kaisa/100/100" },
  { name: "雷克顿", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["恕瑞玛"], job: [], avatar: "https://picsum.photos/seed/tft-renekton/100/100" },
  { name: "内瑟斯", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["恕瑞玛"], job: [], avatar: "https://picsum.photos/seed/tft-nasus/100/100" },
  { name: "卡莉丝塔", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["暗影岛"], job: ["征服者"], avatar: "https://picsum.photos/seed/tft-kalista/100/100" },
  { name: "芸阿娜", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["艾欧尼亚"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-yunana/100/100" },
  { name: "斯维因", season: "英雄联盟传奇 (S16)", cost: 4, origin: ["诺克萨斯"], job: ["法师", "主宰"], avatar: "https://picsum.photos/seed/tft-swain/100/100" },
  { name: "安妮", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["黑暗之女"], job: ["法师"], avatar: "https://picsum.photos/seed/tft-annie/100/100" },
  { name: "奥恩", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["山隐之焰"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-ornn/100/100" },
  { name: "千珏", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["永猎双子"], job: ["迅击战士"], avatar: "https://picsum.photos/seed/tft-kindred/100/100" },
  { name: "阿兹尔", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["恕瑞玛", "沙漠皇帝"], job: ["耀光使"], avatar: "https://picsum.photos/seed/tft-azir/100/100" },
  { name: "基兰", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["时光守护者"], job: ["神谕者"], avatar: "https://picsum.photos/seed/tft-zilean/100/100" },
  { name: "费德提克", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["远古恐惧"], job: ["征服者"], avatar: "https://picsum.photos/seed/tft-fiddlesticks/100/100" },
  { name: "希瓦娜", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["龙血武姬"], job: ["主宰"], avatar: "https://picsum.photos/seed/tft-shyvana/100/100" },
  { name: "加里奥", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["德玛西亚", "正义巨像"], job: [], avatar: "https://picsum.photos/seed/tft-galio/100/100" },
  { name: "塔姆", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["比尔吉沃特", "河流之王"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-tahmkench/100/100" },
  { name: "瑟提", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["艾欧尼亚", "腕豪"], job: [], avatar: "https://picsum.photos/seed/tft-sett/100/100" },
  { name: "海克斯霸龙", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["海克斯机甲", "皮尔特沃夫"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-thex/100/100" },
  { name: "吉格斯", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["祖安", "约德尔人"], job: ["狙神"], avatar: "https://picsum.photos/seed/tft-ziggs/100/100" },
  { name: "亚托克斯", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["暗裔", "暗裔剑魔"], job: ["裁决战士"], avatar: "https://picsum.photos/seed/tft-aatrox_5/100/100" },
  { name: "沃利贝尔", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["弗雷尔卓德"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-volibear/100/100" },
  { name: "梅尔", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["诺克萨斯"], job: ["耀光使"], avatar: "https://picsum.photos/seed/tft-mel/100/100" },
  { name: "泽拉斯", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["恕瑞玛", "远古巫灵"], job: [], avatar: "https://picsum.photos/seed/tft-xerath/100/100" },
  { name: "锤石", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["暗影岛"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-thresh/100/100" },
  { name: "卢锡安与赛娜", season: "英雄联盟传奇 (S16)", cost: 5, origin: ["系魂圣枪"], job: ["枪手"], avatar: "https://picsum.photos/seed/tft-lucian_senna/100/100" },
  { name: "岩宝", season: "英雄联盟传奇 (S16)", cost: 7, origin: ["以绪塔尔"], job: [], avatar: "https://picsum.photos/seed/tft-yanbao/100/100" },
  { name: "奥瑞利安·索尔", season: "英雄联盟传奇 (S16)", cost: 7, origin: ["铸星龙王", "巨神峰"], job: [], avatar: "https://picsum.photos/seed/tft-aurelionsol/100/100" },
  { name: "纳什男爵", season: "英雄联盟传奇 (S16)", cost: 7, origin: ["虚空", "纳什男爵"], job: [], avatar: "https://picsum.photos/seed/tft-baronnashor/100/100" },
  { name: "塞拉斯", season: "英雄联盟传奇 (S16)", cost: 7, origin: ["解脱者"], job: ["法师", "护卫"], avatar: "https://picsum.photos/seed/tft-sylas/100/100" },
  { name: "瑞兹", season: "英雄联盟传奇 (S16)", cost: 7, origin: ["符文法师"], job: [], avatar: "https://picsum.photos/seed/tft-ryze/100/100" },
  { name: "亚恒", season: "英雄联盟传奇 (S16)", cost: 7, origin: ["暗裔", "不落魔锋"], job: [], avatar: "https://picsum.photos/seed/tft-yaheng/100/100" },

  // 瑞兽闹新春 (S4.5)
  { name: "内瑟斯", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["天神"], job: ["摄魂使"], avatar: "https://picsum.photos/seed/tft-nasus-s4/100/100" },
  { name: "崔丝塔娜", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["龙魂"], job: ["神射手"], avatar: "https://picsum.photos/seed/tft-tristana-s4/100/100" },
  { name: "黛安娜", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["灵魂莲华明昼"], job: ["刺客"], avatar: "https://picsum.photos/seed/tft-diana-s4/100/100" },
  { name: "伊莉丝", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["腥红之月"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-elise-s4/100/100" },
  { name: "盖伦", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["三国猛将"], job: ["重装战士"], avatar: "https://picsum.photos/seed/tft-garen-s4/100/100" },
  { name: "茂凯", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["永恒之森"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-maokai-s4/100/100" },
  { name: "奈德丽", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["三国猛将"], job: ["神射手"], avatar: "https://picsum.photos/seed/tft-nidalee-s4/100/100" },
  { name: "崔斯特", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["腥红之月"], job: ["魔法师"], avatar: "https://picsum.photos/seed/tft-tf-s4/100/100" },
  { name: "孙悟空", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["天神"], job: ["重装战士"], avatar: "https://picsum.photos/seed/tft-wukong-s4/100/100" },
  { name: "亚索", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["浪人"], job: ["决斗大师"], avatar: "https://picsum.photos/seed/tft-yasuo-s4/100/100" },
  { name: "布兰德", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["龙魂"], job: ["魔法师"], avatar: "https://picsum.photos/seed/tft-brand-s4/100/100" },
  { name: "菲奥娜", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["玉剑仙"], job: ["决斗大师"], avatar: "https://picsum.photos/seed/tft-fiora-s4/100/100" },
  { name: "塔姆", season: "瑞兽闹新春 (S4.5)", cost: 1, origin: ["福星"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-tahm-s4/100/100" },
  { name: "安妮", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["福星"], job: ["魔法师"], avatar: "https://picsum.photos/seed/tft-annie-s4/100/100" },
  { name: "劫", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["忍者"], job: ["战神"], avatar: "https://picsum.photos/seed/tft-zed-s4/100/100" },
  { name: "迦娜", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["玉剑仙"], job: ["秘术师"], avatar: "https://picsum.photos/seed/tft-janna-s4/100/100" },
  { name: "弗拉基米尔", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["腥红之月"], job: ["摄魂使"], avatar: "https://picsum.photos/seed/tft-vlad-s4/100/100" },
  { name: "派克", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["腥红之月"], job: ["刺客", "战神"], avatar: "https://picsum.photos/seed/tft-pyke-s4/100/100" },
  { name: "蔚", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["三国猛将"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-vi-s4/100/100" },
  { name: "提莫", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["灵魂莲华明昼"], job: ["神射手"], avatar: "https://picsum.photos/seed/tft-teemo-s4/100/100" },
  { name: "诺提勒斯", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["山海绘卷"], job: ["重装战士"], avatar: "https://picsum.photos/seed/tft-nautilus-s4/100/100" },
  { name: "璐璐", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["永恒之森"], job: ["魔法师"], avatar: "https://picsum.photos/seed/tft-lulu-s4/100/100" },
  { name: "嘉文四世", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["三国猛将"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-jarvan-s4/100/100" },
  { name: "贾克斯", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["天神"], job: ["决斗大师"], avatar: "https://picsum.photos/seed/tft-jax-s4/100/100" },
  { name: "洛", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["永恒之森"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-rakan-s4/100/100" },
  { name: "布隆", season: "瑞兽闹新春 (S4.5)", cost: 2, origin: ["龙魂"], job: ["重装战士"], avatar: "https://picsum.photos/seed/tft-braum-s4/100/100" },
  { name: "阿卡丽", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["忍者"], job: ["刺客"], avatar: "https://picsum.photos/seed/tft-akali-s4/100/100" },
  { name: "千珏", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["灵魂莲华明昼"], job: ["裁决使"], avatar: "https://picsum.photos/seed/tft-kindred-s4/100/100" },
  { name: "艾瑞莉娅", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["玉剑仙", "天神"], job: ["宗师"], avatar: "https://picsum.photos/seed/tft-irelia-s4/100/100" },
  { name: "希瓦娜", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["龙魂"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-shyvana-s4/100/100" },
  { name: "卡莉丝塔", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["腥红之月"], job: ["决斗大师"], avatar: "https://picsum.photos/seed/tft-kalista-s4/100/100" },
  { name: "凯南", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["忍者"], job: ["神盾使"], avatar: "https://picsum.photos/seed/tft-kennen-s4/100/100" },
  { name: "努努和威朗普", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["永恒之森"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-nunu-s4/100/100" },
  { name: "希维尔", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["腥红之月"], job: ["神射手"], avatar: "https://picsum.photos/seed/tft-sivir-s4/100/100" },
  { name: "妮蔻", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["山海绘卷"], job: ["秘术师"], avatar: "https://picsum.photos/seed/tft-neeko-s4/100/100" },
  { name: "德莱厄斯", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["福星"], job: ["战神"], avatar: "https://picsum.photos/seed/tft-darius-s4/100/100" },
  { name: "维迦", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["永恒之森"], job: ["魔法师"], avatar: "https://picsum.photos/seed/tft-veigar-s4/100/100" },
  { name: "悠米", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["灵魂莲华明昼"], job: ["秘术师"], avatar: "https://picsum.photos/seed/tft-yuumi-s4/100/100" },
  { name: "卡特琳娜", season: "瑞兽闹新春 (S4.5)", cost: 3, origin: ["三国猛将", "福星"], job: ["刺客"], avatar: "https://picsum.photos/seed/tft-katarina-s4/100/100" },
  { name: "亚托克斯", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["腥红之月"], job: ["重装战士"], avatar: "https://picsum.photos/seed/tft-aatrox-s4/100/100" },
  { name: "莫甘娜", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["玉剑仙"], job: ["摄魂使"], avatar: "https://picsum.photos/seed/tft-morgana-s4/100/100" },
  { name: "奥瑞利安 · 索尔", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["龙魂"], job: ["魔法师"], avatar: "https://picsum.photos/seed/tft-asol-s4/100/100" },
  { name: "科加斯", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["山海绘卷"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-cho-s4/100/100" },
  { name: "霞", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["永恒之森"], job: ["裁决使", "神盾使"], avatar: "https://picsum.photos/seed/tft-xayah-s4/100/100" },
  { name: "奥拉夫", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["龙魂"], job: ["战神"], avatar: "https://picsum.photos/seed/tft-olaf-s4/100/100" },
  { name: "凯尔", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["天神"], job: ["裁决使"], avatar: "https://picsum.photos/seed/tft-kayle-s4/100/100" },
  { name: "瑟庄妮", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["福星"], job: ["重装战士"], avatar: "https://picsum.photos/seed/tft-sejuani-s4/100/100" },
  { name: "慎", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["忍者"], job: ["宗师", "秘术师"], avatar: "https://picsum.photos/seed/tft-shen-s4/100/100" },
  { name: "泰隆", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["玉剑仙"], job: ["刺客"], avatar: "https://picsum.photos/seed/tft-talon-s4/100/100" },
  { name: "泰达米尔", season: "瑞兽闹新春 (S4.5)", cost: 4, origin: ["三国猛将"], job: ["战神", "决斗大师"], avatar: "https://picsum.photos/seed/tft-tryndamere-s4/100/100" },
  { name: "阿兹尔", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["三国猛将"], job: ["枭雄", "神盾使"], avatar: "https://picsum.photos/seed/tft-azir-s4/100/100" },
  { name: "奥恩", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["永恒之森"], job: ["铁匠", "重装战士"], avatar: "https://picsum.photos/seed/tft-ornn-s4/100/100" },
  { name: "斯维因", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["龙魂"], job: ["摄魂使"], avatar: "https://picsum.photos/seed/tft-swain-s4/100/100" },
  { name: "莎弥拉", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["主宰"], job: ["神射手", "战神"], avatar: "https://picsum.photos/seed/tft-samira-s4/100/100" },
  { name: "李青", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["天神"], job: ["决斗大师"], avatar: "https://picsum.photos/seed/tft-leesin-s4/100/100" },
  { name: "瑟提", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["霸王"], job: ["斗士"], avatar: "https://picsum.photos/seed/tft-sett-s4/100/100" },
  { name: "永恩", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["浪人"], job: ["宗师"], avatar: "https://picsum.photos/seed/tft-yone-s4/100/100" },
  { name: "基兰", season: "瑞兽闹新春 (S4.5)", cost: 5, origin: ["腥红之月"], job: ["秘术师"], avatar: "https://picsum.photos/seed/tft-zilean-s4/100/100" },
];
